# +----------------------------------------------------------------------------+
# | ServerCaster Config                                                        |
# +----------------------------------------------------------------------------+
# |Created by: Patrick Beuks                                                   |
# +----------------------------------------------------------------------------+
# |Make sure that you NEVER use tabs. Always use spaces or bukkit will complain|
# +----------------------------------------------------------------------------+
Prefix: '&RED;{[Broadcast]:}'