name: ServerCasterExtension
author: [Patrick-Beuks]
description: This plugin adds a few extra commands to ServerCaster 1.8+
version: 1.9-SNAPSHOT
main: me.patrick.servercaster.extension.ServerExtension
depend: [ServerCaster]